# Generated by Django 4.1.3 on 2022-12-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
