# Generated by Django 4.1.3 on 2022-12-14 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_messages', '0002_alter_conversations_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesages',
            new_name='Messages',
        ),
    ]
