# Generated by Django 4.1.3 on 2022-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_messages', '0003_rename_mesages_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='unread_messages',
        ),
        migrations.AddField(
            model_name='messages',
            name='message_unread',
            field=models.BooleanField(default=True),
        ),
    ]
