# Generated by Django 4.1.3 on 2022-12-14 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_messages', '0004_remove_conversations_unread_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='last_unread_message_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
