# Generated by Django 4.1.3 on 2022-12-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autors',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('book_id',)},
        ),
    ]
