# Generated by Django 4.1.3 on 2022-12-05 07:34

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_autors_options_alter_books_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='images', validators=[books.validators.image_size_validator]),
        ),
    ]
