# Generated by Django 4.1.3 on 2022-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Fantasy', 'Fantasy'), ('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Crime', 'Crime'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Biography', 'Biography'), ('Poetry', 'Poetry'), ('History', 'History'), ('Other', 'Other')], max_length=30),
        ),
    ]
