# Generated by Django 4.1.3 on 2022-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='return_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
