# Generated by Django 4.1.3 on 2022-12-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_books_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrow_counter',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
