# Generated by Django 4.1.3 on 2022-12-07 12:54

import books.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_books_borrow_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[books.validators.image_size_validator]),
        ),
    ]
