# Generated by Django 4.1.3 on 2022-12-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_books_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('-book_id',)},
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=234),
        ),
    ]
