# Generated by Django 4.1.3 on 2022-12-02 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Authors', 'Authors'), ('Publishers', 'Publishers'), ('Other', 'Other')], max_length=30)),
                ('topic_creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('comments_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('topic_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_post', models.TextField(max_length=333)),
                ('date_time_of_post', models.DateTimeField(auto_now_add=True)),
                ('topic_to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topics')),
            ],
        ),
    ]
