# Generated by Django 4.1.3 on 2022-12-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_topic_to_post_posts_post_to_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='topic_author',
            new_name='post_author',
        ),
    ]
