# Generated by Django 4.1.3 on 2022-12-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_topic_author_posts_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='comments_count',
        ),
    ]
