# Generated by Django 4.1.3 on 2022-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_topics_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='comments_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
