# Generated by Django 4.1.3 on 2022-12-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topics_comments_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='comments_count',
            new_name='posts_count',
        ),
    ]
